# Generated by Django 5.2.8 on 2025-11-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(help_text='Universal Product Code', max_length=5, unique=True)),
                ('name', models.CharField(help_text='Product Name', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Product Price', max_digits=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
